allowBuilds:
  ' ': true
  a: true
  b: true
  c: true
  d: true
  e: true
  electron: false
  esbuild: false
  h: true
  i: true
  l: true
  n: true
  o: true
  p: true
  r: true
  s: true
  sharp: false
  t: true
  u: true
